### ISSUE TITLE
imagemagick package not available on Windows

### ISSUE THREAD

**Issue by saphiresouldier** [google/samurai#6]
The conda environment creation done with 
`conda env create -f environment.yml`
fails on Windows devices due to the **imagemagick** package not being available with conda-forge:
[https://anaconda.org/conda-forge/imagemagick](https://anaconda.org/conda-forge/imagemagick)

It seems there are no conda channels featuring windows versions of this package available according to a [quick search](https://anaconda.org/search?q=imagemagick).

**Comment by vork** [comment]
We're not supporting Windows. Data preparation will most likely not work on Windows and there might be other issues.

We recommend using Ubuntu.

**Comment by saphiresouldier** [comment]
Ah I thought so, thanks for clarifying! Might be worth mentioning in a short sentence with the Setup instructions of the readme?
